sudo: required
# super user persmission
services:
  - docker

before_install:
  - docker build -t shmanu17/docker-react -f Dockerfile.dev .
  # . is used for using the current directory

script:
  - docker run shmanu17/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-855855432963"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY