sudo: required
# super user persmission
services:
  - docker

before_install:
  - docker build -t shmanu17/docker-react -f Dockerfile.dev .
  # . is used for using the current directory

script:
  - docker run shmanu17/docker-react npm run test -- --coverage
  - npm run eject